package fan.dnd.dndcharactergeneratorkotlin.domain.spells.wizard

enum class WizardSpell4level(val id: Int) {
    ARCANE_EYE(16),
    BANISHMENT(29),
    BLIGHT(39),
    CONFUSION(69),
    CONJURE_MINOR_ELEMENTALS(75),
    CONTROL_WATER(83),
    DIMENSION_DOOR(108),
    ELEMENTAL_BANE(128),
    EVARD_S_BLACK_TENTACLES(137),
    FABRICATE(140),
    FIRE_SHIELD(154),
    GREATER_INVISIBILITY(180),
    HALLUCINATORY_TERRAIN(191),
    ICE_STORM(208),
    LEOMUND_S_SECRET_CHEST(224),
    LOCATE_CREATURE(233),
    MORDENKAINEN_S_FAITHFUL_HOUND(267),
    MORDENKAINEN_S_PRIVATE_SANCTUM(269),
    OTILUKE_S_RESILIENT_SPHERE(275),
    PHANTASMAL_KILLER(281),
    POLYMORPH(288),
    STONE_SHAPE(352),
    STONESKIN(353),
    STORM_SPHERE(355),
    VITRIOLIC_SPHERE(388),
    WALL_OF_FIRE(389),
    WATERY_SPHERE(400)

}
